### PR TITLE
Failing integration test: Add and delete client RedirectUri values

### PR DESCRIPTION
**Pull request by kendaleiv**
Not sure if this is a bug or I'm doing it wrong, but I've created an integration test for a scenario I believe should work with creating and deleting client **RedirectUris** values. This should be a failing test.

If you want to merge this in later for any reason I can rebase, I'm aware this isn't mergeable in its current form.

### CODE REVIEW

**Comment by brockallen** [comment]
I just switched the tests over to xUnit today -- I think you missed my commit by like an hour.

**Comment by kendaleiv** [comment]
No worries -- it's an easy switch, if you want to pull this in for any reason.

**Comment by brockallen** [comment]
Why the hell not -- more tests are a good thing :)

**Comment by brockallen** [comment]
Oh and I've seen you code -- so I pretty much trust any test you'd write for me!

**Comment by kendaleiv** [comment]
Well, this one is currently failing, and is the reason for the PR.

Failing for me, anyhow...

**Comment by kendaleiv** [comment]
Let me know if you'd like it rewritten with xunit before you look into it, if it makes things considerably easier.

**Comment by brockallen** [comment]
So yea, go ahead and port them over (er, really just grab latest on dev and move them over). Once you've done that, then it'll be more clear to me what's what.

**Comment by kendaleiv** [comment]
Closing, see #53.

**Pull request closed without merging**
